### ISSUE TITLE
chain maker does not respect case

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-cm#25]
`eris chains make idiApp (assume >1 accounts)`

`ls ~/.eris/chains/idiApp/` 
expected  => `idiApp_full_000`
got:          => `idiapp_full_000`

**Comment by AFDudley** [comment]
Keep in mind that OSX is case insensitive by default. 😦

**Comment by zramsay** [comment]
Not sure if OSX behaviour is relevant here. Basically, I ran into this issue while editing [this line](https://github.com/eris-ltd/coding/blob/master/contracts/idi/app.js#L22) for the [contract interacting tut](https://github.com/eris-ltd/docs.erisindustries.com/blob/master/tutorials/contracts-interacting.md)

My intuition was to `accountData.idiApp_full_000` but that threw an error when running the app.js...at which point I discovered the culprit; that all the account dirs were lowercased. #26 is the fix

**Comment by AFDudley** [comment]
if eris-cli is running on osx and a user thinks that those are two different directories, they are going to have a bad time. When you get around to writing the test for this on OSX you're going to have problems. ToLower() was the correct behavior.

**Comment by AFDudley** [comment]
The better thing to do would be to check if lower actually changed the string, and if it did, throw a warning to the user.

**Comment by AFDudley** [comment]
or apply lower only in case-insensitive environments (not sure how to test for that.)

**Comment by zramsay** [comment]
obsolete
