### ISSUE TITLE
Upgrade existing chains functionality to be added to eris-cm

### ISSUE THREAD

**Issue by benjaminbollen** [eris-ltd/eris-cm#28]
Copied from https://github.com/eris-ltd/eris-db/issues/155:
1. Eris-DB v0.11.4 and prior read config.toml by Tendermint and server_conf.toml by Eris-DB; as of 0.12.0-rc2 Eris-DB reads a single server_config.toml
2. As of Eris-DB v0.12.0rc2 the state database is (by default) separated from the consensus engine block store; but on existing chains (Eris-DB v0.11.4) these files are in the same directory; make sure Eris-DB v0.12.0 configures itself for a single shared directory for existing chains.

**Comment by compleatang** [comment]
This isn't going to happen. Unfortunately users are going to need to manually upgrade their chains from 0.11 to 0.12 chains. Moving the issue to 0.12.1|0.16.0

**Comment by compleatang** [comment]
Issue moved to [eris-ltd/eris-cli #1010](https://github.com/eris-ltd/eris-cli/issues/1010) via [**ZenHub**](https://www.zenhub.com/)
