### ISSUE TITLE
Create unit tests

### ISSUE THREAD

**Issue by AFDudley** [eris-ltd/eris-cm#34]
Not entirely sure what else to say, but we should discuss it and put it on a roadmap.

**Comment by benjaminbollen** [comment]
@AFDudley would it make sense to first test the `go test` unit test framework for e-cm, before launching off into the more expensive (in time and infrastructure cost) launch of aws machine that installs docker and pulls the other eris images; for integration / acceptance tests?

**Comment by benjaminbollen** [comment]
also, it seems the current e-cm testing cycle does not run `go test` :)

**Comment by AFDudley** [comment]
Yes. We need to run `build_lin` and `test_lin` jobs before running `build_DI` jobs. We then have to run the `test_DI` scripts against a whole ton of configurations.

**Comment by compleatang** [comment]
Issue moved to [eris-ltd/eris-cli #1009](https://github.com/eris-ltd/eris-cli/issues/1009) via [**ZenHub**](https://www.zenhub.com/)
