### ISSUE TITLE
Binary testing

### ISSUE THREAD

**Issue by AFDudley** [eris-ltd/eris-cm#35]
Do we need to test these binaries? if so, what platforms are we supporting?

**Comment by compleatang** [comment]
we don't publish binaries outside of docker images, so we need to test the docker image via the repo's stacktests along with our tooltests (go tests/unit tests) which should be handled in #34

**Comment by AFDudley** [comment]
The more I think about it, the more I'm convinced this doesn't make any sense. If we make command line tools and test the command line tools, we should release them as packages just like `eris cli`. If we don't release them as packages just like `eris cli` then we shouldn't be making them and testing them, instead we should be using them as libraries inside of `eris cli` and `eris db`.

**Comment by compleatang** [comment]
cm will become a library. closing this issue.
