### ISSUE TITLE
Easier method to add users

### ISSUE THREAD

**Issue by dennismckinnon** [eris-ltd/eris-cm#38]
I have had a few people express confusion on how to maintain a chain through its lifecycle such as adding new users and modifying permissions etc.  Maybe this is a matter of clarifying how to access these components or maybe we need to build nicer fronts to these features IDK

**Comment by compleatang** [comment]
Issue moved to [eris-ltd/eris-cli #1008](https://github.com/eris-ltd/eris-cli/issues/1008) via [**ZenHub**](https://www.zenhub.com/)
