### ISSUE TITLE
add config.toml building to the sequencing.

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cm#5]

**Comment by compleatang** [comment]
I'm not totally sure how we would do this. Perhaps with a `--root-ip` flag which will set the IP:port combo of the peer server? Sometimes that will be known and sometimes it will not be known when chains make is run. We could also have a config maker command that will take an array of IP:port combinations and add those into the configs. 

Let's discuss this during the upcoming week. For now am going to reassign this to @AFDudley as he's got some strong opinions here :)

**Comment by AFDudley** [comment]
I am confused about where in the code this is actually happening...
https://github.com/eris-ltd/eris-cm/blob/master/maker/mint_chains.go
has no relation to
https://github.com/AFDudley/eris-cli/blob/develop/chains/manage.go#L43
?

**Comment by compleatang** [comment]
The cli is mostly irrelevant to this issue. All `chains make' in the cli is doing is running `eris-cm make` in a docker container. 

The easiest way to do this is to add a config.go to the maker directory. In that file add a MakeConfig command and a base struct which has the defaults from the config.toml. Then in the MakeConfig function you can update moniker, IP:port,  etc. As needed and then write the file into the correct directories. 

Next, I'd add the proper flags to this repository in the cmd/maker.go file. Finally I'd call MakeConfig from MakeChain before that switch statement. 

The final step would be to add the appropriate flags to `eris chains make` in the cli repo and have the "flow thru" to the wrapped containers EntryPoint.

**Comment by compleatang** [comment]
@benjaminbollen formally assigning this to you since you've been working on it. :)

**Comment by zramsay** [comment]
can basically just re-implement https://github.com/eris-ltd/mint-client/blob/master/mintconfig/cli.go#L12-30

**Comment by benjaminbollen** [comment]
I am working my way up from e-db, on reworking the config; so I will either bring in line these config flags with the new configfile for edb; or take this issue on when I can move from e-db to e-cm

**Comment by zramsay** [comment]
closed by #29?

**Comment by compleatang** [comment]
closed no?
