### ISSUE TITLE
`eris-cm make --ip` 

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-cm#50]
**Problem:** manually setting the IP in the `config.toml` is a PITA and requires extra bash to automate

**Solution:** flag to set the default IP of a "root" peer, to whom everyone dials into.

**Comment by compleatang** [comment]
Issue moved to [eris-ltd/eris-cli #1007](https://github.com/eris-ltd/eris-cli/issues/1007) via [**ZenHub**](https://www.zenhub.com/)
