### ISSUE TITLE
`eris-cm` returns exit code 0 on illegal commands

### ISSUE THREAD

**Issue by pietv** [eris-ltd/eris-cm#51]
```
$ ./eris-cm random; echo $?
Error: unknown command "random" for "eris-cm"
Run 'eris-cm --help' for usage.
0
```
CLI runs `eris-cm` as a Docker container, and it judges normal CM behavior by its exit code. It is useful to capture a `eris-cm` error when new commands or flags are added to it or renamed.

**Comment by compleatang** [comment]
closing as a no fix prior to repository consolidation
